### ISSUE TITLE
possible to get an updated version?

### ISSUE THREAD

**Issue by benmarwick** [kjhealy/kjh-vita#1]
Thanks for sharing this, I notice that the pdf generated by this script is a just a tiny bit less elegant than the one you link to here: http://kieranhealy.org/resources/ Would it be possible for you to share your current template? thanks!

**Comment by kjhealy** [comment]
No problem. I'll put it on the to-do list.

**Comment by benmarwick** [comment]
Brilliant, thanks very much, that works great. Also works with these free fonts (handy because they have huge glyph sets & are readily available to students, etc.):

Minion Pro -> Linux Libertine http://www.linuxlibertine.org/index.php?id=2&L=1
Unit-Medium  -> Linux Biolinum http://www.linuxlibertine.org/index.php?id=2&L=1
PragmataPro -> Ubuntu http://font.ubuntu.com/
